graph LR;
    A((Start)) --> B{"Does args have at least 2 elements?"};
    B -- "Yes" --> C["Assign name1 = args[0]"];
    C --> D["Assign name2 = args[1]"];
    D --> E[/"Print 'Hello ' + name1 + ' and ' + name2 + '.'" /];
    E --> F[/"Print 'Goodbye ' + name2 + ' and ' + name1 + '.'" /];
    F --> G((End));
    B -- "No" --> G;
