graph TD; subgraph "enqueue"; A((Start))-->B{n==len?}; B--Yes-->C[resize]; C-->D[add item]; B--No-->D; D-->E((End)); end; subgraph "dequeue"; F((Start))-->G{isEmpty?}; G--Yes-->H[Exception]; G--No-->I[...]; I-->J((End)); end
