graph LR;
    A((Start open)) --> B["validate(row, col)"];
    B --> C{"isOpen(row, col)?"};
    C -- "Yes" --> Z((End));
    C -- "No" --> D["grid[row-1][col-1] = true<br>openSites++"];
    D --> E{"row == 1?"};
    E -- "Yes" --> F["union(site, top)"];
    E -- "No" --> G;
    F --> G{"row == n?"};
    G -- "Yes" --> H["union(site, bottom)"];
    G -- "No" --> I;
    H --> I["Check & union with<br>open neighbors"];
    I --> Z;
