graph TD
    A[Start] --> B["deque = new Deque<Integer>()"];
    B --> C["System.out.println(&quot;Is empty? &quot; + deque.isEmpty())"];
    C --> D[deque.addFirst(1)];
    D --> E[deque.addLast(2)];
    E --> F["System.out.println(&quot;Size: &quot; + deque.size())"];
    F --> G[For each int i in deque];
    G --> H["System.out.println(i)"];
    H --> G;
    G --> I["System.out.println(&quot;Removed first: &quot; + deque.removeFirst())"];
    I --> J["System.out.println(&quot;Removed last: &quot; + deque.removeLast())"];
    J --> K["System.out.println(&quot;Size: &quot; + deque.size())"];
    K --> L[End];
